gem 'rails', '3.2.21'
gem 'thin'
gem "therubyracer"
gem 'jquery-rails'
gem 'devise'
gem 'stripe'
gem 'stripe_event'
gem 'http_accept_language'
gem 'sass-rails',   '~> 3.2.3'
gem 'uglifier', '>= 1.0.3'
gem 'quiet_assets'
gem 'sqlite3'
gem 'rspec-rails', '2.99'
gem 'factory_girl_rails'
gem 'faker'
gem 'capybara'
gem 'guard-rspec'
gem 'launchy'
gem 'poltergeist'
gem 'email_spec'
gem 'webmock'
gem 'vcr'
gem 'mysql2'

