source 'https://rubygems.org'
ruby '2.3.0'
gem 'rails', '~>4.2'

gem 'active_model_serializers'
gem 'acts_as_list'
gem 'airbrussh', require: false
gem 'animate-scss'
gem 'attr_extras'
gem 'autoprefixer-rails'
gem 'capistrano'
gem 'capistrano-docker', github: 'netguru/capistrano-docker', tag: 'v0.2.5'
gem 'carrierwave'
gem 'coffee-rails'
gem 'coffee-script-source'
gem 'decent_decoration'
gem 'decent_exposure'
gem 'devise'
gem 'dotenv-rails'
gem 'draper'
gem 'flip'
gem 'fog'
gem 'font-awesome-rails'
gem 'gon'
gem 'google-analytics-rails'
gem 'google-api-client', require: 'google/api_client'
gem 'haml-rails'
gem 'haml_coffee_assets', github: 'netzpirat/haml_coffee_assets'
gem 'httparty'
gem 'i18n-js', '>= 3.0.0.rc11'
gem 'jquery-cookie-rails'
gem 'jquery-rails'
gem 'jquery-tablesorter'
gem 'jquery-ui-rails'
gem 'js_stack'
gem 'konf'
gem 'messengerjs-rails'
gem 'mini_magick'
gem 'netguru_theme'
gem 'newrelic_rpm'
gem 'oj'
gem 'omniauth'
gem 'omniauth-github'
gem 'omniauth-google-oauth2'
gem 'pg'
gem 'pundit'
gem 'rabl'
gem 'rack-mini-profiler', require: false
gem 'rake-progressbar'
gem 'react_webpack_rails'
gem 'render_anywhere', require: false
gem 'restforce'
gem 'retriable'
gem 'rollbar'
gem 'sass-rails'
gem 'searchlight'
gem 'selectize-rails'
gem 'simple_form'
gem 'slack-notifier'
gem 'sucker_punch'
gem 'therubyracer'
gem 'uglifier'
gem 'versionist'
gem 'virtus'
gem 'whenever', require: false
gem 'httparty'
gem 'active_model_serializers'
gem 'react_webpack_rails'
gem 'rake-progressbar'
gem 'rack-cors', require: 'rack/cors'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'bullet'
  gem 'gemsurance'
  gem 'guard-rails'
  gem 'guard-rspec'
  gem 'guard-rubocop'
  gem 'letter_opener'
  gem 'quiet_assets'
  gem 'spring-commands-rspec'
end

group :development, :test do
  gem 'awesome_print'
  gem 'capistrano-rvm', require: false
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-rails'
end

group :test do
  gem 'capybara'
  gem 'capybara-screenshot'
  gem 'capybara-webkit'
  gem 'codeclimate-test-reporter', require: false
  gem 'database_cleaner'
  gem 'rack_session_access'
  gem 'rspec-its'
  gem 'rspec-rails'
  gem 'selenium-webdriver'
  gem 'shoulda'
  gem 'site_prism'
  gem 'timecop'
end

group :staging, :production do
  gem 'lograge'
end
